# Generated by Django 3.1.2 on 2020-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products', verbose_name='Maxsulot rasmi')),
                ('title', models.CharField(max_length=255, verbose_name='Maxsulot rasmi')),
                ('slug', models.SlugField(verbose_name='Ssilka')),
            ],
        ),
    ]
