# Generated by Django 3.1.2 on 2020-12-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoriya')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Maxsulot Haqida'),
        ),
        migrations.AddField(
            model_name='product',
            name='prise',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Narxini kiriting'),
        ),
        migrations.CreateModel(
            name='SubCategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='SubCategoriyani kiriting')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.categoryproduct', verbose_name='Categoriyani tanlang')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='prodThumbImg', verbose_name="Qo'shimcha rasm")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Maxsulot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productfeatures', models.CharField(max_length=255, verbose_name='Maxsulot Xususiyati nomi')),
                ('productfeaturestext', models.CharField(max_length=255, verbose_name='Maxsulot Xususiyati')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Maxsulot')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct', verbose_name='Categoriya'),
        ),
    ]
