# Generated by Django 3.1.2 on 2020-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201218_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hamkorning nomi')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Hamkorning logotipi')),
            ],
        ),
    ]
