# Generated by Django 3.1.2 on 2020-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('text', models.TextField(verbose_name='Maqola')),
                ('slug', models.SlugField(max_length=255, verbose_name='link')),
            ],
        ),
    ]
