# Generated by Django 3.1.2 on 2020-12-19 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Galereyaga sarlavha')),
                ('date', models.DateField(default=datetime.datetime(2020, 12, 19, 9, 30, 56, 359080, tzinfo=utc), verbose_name='galerreya qoshilgan vaqti')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Rasm')),
                ('slug', models.SlugField(max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gallery', verbose_name='Galereya')),
            ],
        ),
    ]
