# Generated by Django 3.1.2 on 2020-12-19 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery_gallerydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='galerreya qoshilgan vaqti'),
        ),
    ]
