# Generated by Django 3.1.2 on 2020-12-19 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201219_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('letter', models.TextField(verbose_name='Maqola')),
                ('img', models.ImageField(upload_to='newsletter', verbose_name='rasm')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Maqola yozilgan sana ')),
            ],
        ),
        migrations.AlterField(
            model_name='gallerydetail',
            name='img',
            field=models.ImageField(upload_to='gallery', verbose_name='Rasm'),
        ),
    ]
