# Generated by Django 3.1.2 on 2020-12-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201219_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifikatning nomi')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Sertifikatning rasmi')),
            ],
        ),
    ]
